version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8089:8083"
    container_name: ${PROJECT_NAME}-nginx
    depends_on:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  laravel:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - cache
      - postgres
    volumes:
      - ./laravel/:/var/www/laravel
    working_dir: /var/www/laravel
    container_name: ${PROJECT_NAME}-laravel
    command: bash -c "php artisan octane:start --host=0.0.0.0 --port=8000 --watch"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:17.0
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - 5432
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    restart: always

  phppgadmin:
    container_name: ${PROJECT_NAME}-phppgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: 1111

  cache:
    image: redis:6.2-alpine
    restart: always
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    container_name: ${PROJECT_NAME}-cache
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
